version: "3.8"


services:

  example-db:
    image: library/postgres:13
    restart: unless-stopped
    ports:
      - "5458:5432"
    environment:
      DB_NAME: "postgres"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_PORT: "5454"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./resources/dvdrental:/dvdrental
